// ====== LANGUAGES CONFIGURATION ======
const LANGUAGES = {
    en: {
        code: 'en',
        name: 'English',
        teacherName: 'Emma',
        flag: 'flag_en.jpg',
        face: 'face_en.jpg',
        gif: 'gif_en.gif',
        video: 'video_en.mp4',
        speechLang: 'en-US',
        femaleVoices: ['female', 'woman', 'girl', 'samantha', 'zira', 'google', 'english'],
        youglishLang: 'english',
        teacherTitle: 'English Teacher',
        aiPromptLang: 'English',
        translatorBtnLabel: 'TRANSLATOR',
        lessonBtnLabel: 'LESSON',
        grammarBtnLabel: 'GRAMMAR',
        grammarPlusBtnLabel: 'GRAMMAR+',
        pronunciationBtnLabel: 'PRONUNCIATION'
    },
    de: {
        code: 'de',
        name: 'Deutsch',
        teacherName: 'Greta',
        flag: 'flag_de.jpg',
        face: 'face_de.jpg',
        gif: 'gif_de.gif',
        video: 'video_de.mp4',
        speechLang: 'de-DE',
        femaleVoices: ['female', 'woman', 'katja', 'hedda', 'marlene', 'vicki', 'google deutsch', 'deutsch'],
        youglishLang: 'german',
        teacherTitle: 'Deutschlehrerin',
        aiPromptLang: 'German (Deutsch)',
        translatorBtnLabel: 'ÜBERSETZERIN',
        lessonBtnLabel: 'LEKTION',
        grammarBtnLabel: 'GRAMMATIK',
        grammarPlusBtnLabel: 'GRAMMATIK+',
        pronunciationBtnLabel: 'AUSSPRACHE'
    },
    fr: {
        code: 'fr',
        name: 'Français',
        teacherName: 'Camille',
        flag: 'flag_fr.jpg',
        face: 'face_fr.jpg',
        gif: 'gif_fr.gif',
        video: 'video_fr.mp4',
        speechLang: 'fr-FR',
        femaleVoices: ['female', 'woman', 'hortense', 'julie', 'celine', 'google français', 'français'],
        youglishLang: 'french',
        teacherTitle: 'Professeure de Français',
        aiPromptLang: 'French (Français)',
        translatorBtnLabel: 'TRADUCTRICE',
        lessonBtnLabel: 'LEÇON',
        grammarBtnLabel: 'GRAMMAIRE',
        grammarPlusBtnLabel: 'GRAMMAIRE+',
        pronunciationBtnLabel: 'PRONONCIATION'
    },
    it: {
        code: 'it',
        name: 'Italiano',
        teacherName: 'Chiara',
        flag: 'flag_it.jpg',
        face: 'face_it.jpg',
        gif: 'gif_it.gif',
        video: 'video_it.mp4',
        speechLang: 'it-IT',
        femaleVoices: ['female', 'woman', 'elsa', 'cosimo', 'alice', 'federica', 'google italiano', 'italiano'],
        youglishLang: 'italian',
        teacherTitle: "Insegnante d'Italiano",
        aiPromptLang: 'Italian (Italiano)',
        translatorBtnLabel: 'TRADUTTRICE',
        lessonBtnLabel: 'LEZIONE',
        grammarBtnLabel: 'GRAMMATICA',
        grammarPlusBtnLabel: 'GRAMMATICA+',
        pronunciationBtnLabel: 'PRONUNCIA'
    },
    pt: {
        code: 'pt',
        name: 'Português',
        teacherName: 'Inês',
        flag: 'flag_pt.jpg',
        face: 'face_pt.jpg',
        gif: 'gif_pt.gif',
        video: 'video_pt.mp4',
        speechLang: 'pt-PT',
        femaleVoices: ['female', 'woman', 'helena', 'raquel', 'luciana', 'google português', 'português'],
        youglishLang: 'portuguese',
        teacherTitle: 'Professora de Português',
        aiPromptLang: 'Portuguese (Português)',
        translatorBtnLabel: 'TRADUTORA',
        lessonBtnLabel: 'LIÇÃO',
        grammarBtnLabel: 'GRAMÁTICA',
        grammarPlusBtnLabel: 'GRAMÁTICA+',
        pronunciationBtnLabel: 'PRONÚNCIA'
    },
    ru: {
        code: 'ru',
        name: 'Русский',
        teacherName: 'Anastasia',
        flag: 'flag_ru.jpg',
        face: 'face_ru.jpg',
        gif: 'gif_ru.gif',
        video: 'video_ru.mp4',
        speechLang: 'ru-RU',
        femaleVoices: ['female', 'woman', 'irina', 'tatyana', 'elena', 'google русский', 'русский'],
        youglishLang: 'russian',
        teacherTitle: 'Преподаватель русского',
        aiPromptLang: 'Russian (Русский)',
        translatorBtnLabel: 'ПЕРЕВОДЧИЦA',
        lessonBtnLabel: 'УРОК',
        grammarBtnLabel: 'ГРАММАТИКА',
        grammarPlusBtnLabel: 'ГРАММАТИКА+',
        pronunciationBtnLabel: 'ПРОИЗНОШЕНИЕ'
    },
    ca: {
        code: 'ca',
        name: 'Català',
        teacherName: 'Montserrat',
        flag: 'flag_ca.jpg',
        face: 'face_ca.jpg',
        gif: 'gif_ca.gif',
        video: 'video_ca.mp4',
        speechLang: 'ca-ES',
        femaleVoices: ['female', 'woman', 'montserrat', 'laia', 'joana', 'google català', 'català', 'valencian'],
        youglishLang: 'catalan',
        teacherTitle: 'Professora de Català',
        aiPromptLang: 'Catalan (Català)',
        translatorBtnLabel: 'TRADUCTORA',
        lessonBtnLabel: 'LLIÇÓ',
        grammarBtnLabel: 'GRAMÀTICA',
        grammarPlusBtnLabel: 'GRAMÀTICA+',
        pronunciationBtnLabel: 'PRONÚNCIA'
    },
    eu: {
        code: 'eu',
        name: 'Euskara',
        teacherName: 'Amaia',
        flag: 'flag_eu.jpg',
        face: 'face_eu.jpg',
        gif: 'gif_eu.gif',
        video: 'video_eu.mp4',
        speechLang: 'eu-ES',
        femaleVoices: ['female', 'woman', 'amaia', 'miren', 'aritz', 'google euskara', 'basque', 'euskara'],
        youglishLang: 'basque',
        teacherTitle: 'Euskara Irakaslea',
        aiPromptLang: 'Basque (Euskara)',
        translatorBtnLabel: 'ITZULTZAILEA',
        lessonBtnLabel: 'IKASGAIA',
        grammarBtnLabel: 'GRAMATIKA',
        grammarPlusBtnLabel: 'GRAMATIKA+',
        pronunciationBtnLabel: 'AHOSKERA'
    },
    gl: {
        code: 'gl',
        name: 'Galego',
        teacherName: 'Iria',
        flag: 'flag_gl.jpg',
        face: 'face_gl.jpg',
        gif: 'gif_gl.gif',
        video: 'video_gl.mp4',
        speechLang: 'gl-ES',
        femaleVoices: ['female', 'woman', 'iria', 'carme', 'sabela', 'google galego', 'galician', 'galego'],
        youglishLang: 'galician',
        teacherTitle: 'Profesora de Galego',
        aiPromptLang: 'Galician (Galego)',
        translatorBtnLabel: 'TRADUTORA',
        lessonBtnLabel: 'LECCIÓN',
        grammarBtnLabel: 'GRAMÁTICA',
        grammarPlusBtnLabel: 'GRAMÁTICA+',
        pronunciationBtnLabel: 'PRONUNCIA'
    }
};
